### ISSUE TITLE
unit testing plugin

### ISSUE THREAD

**Issue by indratan** [EXXETA/sonar-esql-plugin#10]
Hi.
we have been using this esql plugin for our sonar instance.
we are wondering if there is "unit testing" module/coverage for sonar ESQL.
I personally don't think it exist, but need to confirm with you guys.

please advise.
thank you in advance
Indra

**Comment by ThomasPohl** [comment]
Hi,
there might be a possibility to implment such a feature simmilar to IAM2: ftp://public.dhe.ibm.com/software/integration/support/supportpacs/individual/iam2.pdf

Today there is no such feature implemented in the sonar esql plugin.

Thomas

**Comment by ThomasPohl** [comment]
Starting with version 2.2.0 the plugin will have a test coverage functionality.
I hope this feature is, what you where missing.
