### ISSUE TITLE
Parse error on ESQL CREATE FUNCTION with CLASSLOADER keyword

### ISSUE THREAD

**Issue by djshea** [EXXETA/sonar-esql-plugin#116]
ESQL CREATE FUNCTION returns parse error if the CLASSLOADER keyword is used.
For example....

CREATE FUNCTION MyFunc( IN param01 CHAR ) RETURNS CHARACTER
    LANGUAGE JAVA
    EXTERNAL NAME "abc.def.myStuff"
    CLASSLOADER "{My_Java_SharedLib}";

will return a parse error pointing to the line with the CLASSLOADER keyword.

**Comment by ThomasPohl** [comment]
Thanks for your bug report. I added a fix and will include it in the next bugfix release. I think hink you are the first using the plugin to parse classloader settings. Issue #39 exists for 2 years now and no-one was interested in it. ;)
