### ISSUE TITLE
When Upgrading SonarScanner from Version 3.2 to 4.2 I recieved JAXBException when attempting to Parse Usertrace.xml file

### ISSUE THREAD

**Issue by RSPalazzo** [EXXETA/sonar-esql-plugin#117]
Hello,

Seems jumping a version on the Sonar Scanner has broken the parsing of the XML file 

Below I have attached the full version of the Error log and the Usertrace file

15:28:28  15:28:28.054 INFO: Analysing D:\Jenkins\workspace\iibTrace\usertrace.xml
15:28:28  15:28:28.061 INFO: 3/3 source files have been analyzed
15:28:28  15:28:28.092 INFO: ------------------------------------------------------------------------
15:28:28  15:28:28.092 INFO: EXECUTION FAILURE
15:28:28  15:28:28.092 INFO: ------------------------------------------------------------------------
15:28:28  15:28:28.093 INFO: Total time: 9.122s
15:28:28  15:28:28.154 INFO: Final Memory: 13M/54M
15:28:28  15:28:28.154 INFO: ------------------------------------------------------------------------
15:28:28  15:28:28.154 ERROR: Error during SonarQube Scanner execution
15:28:28  java.lang.RuntimeException: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
15:28:28   - with linked exception:
15:28:28  [java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
15:28:28  	at com.exxeta.iss.sonar.esql.codecoverage.TraceFileReader.readXML(TraceFileReader.java:104)
15:28:28  	at com.exxeta.iss.sonar.esql.codecoverage.TraceFileReader.readTrace(TraceFileReader.java:64)
15:28:28  	at com.exxeta.iss.sonar.esql.codecoverage.AbstractAnalyzer.analyse(AbstractAnalyzer.java:63)
15:28:28  	at com.exxeta.iss.sonar.esql.codecoverage.TraceSensor.execute(TraceSensor.java:44)
15:28:28  	at com.exxeta.iss.sonar.esql.EsqlSensor.executeCoverageSensors(EsqlSensor.java:346)
15:28:28  	at com.exxeta.iss.sonar.esql.EsqlSensor.executeCoverageSensors(EsqlSensor.java:338)
15:28:28  	at com.exxeta.iss.sonar.esql.EsqlSensor.execute(EsqlSensor.java:307)
15:28:28  	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
15:28:28  	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
15:28:28  	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
15:28:28  	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
15:28:28  	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
15:28:28  	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)

[usertrace.xml.txt](https://github.com/EXXETA/sonar-esql-plugin/files/4269034/usertrace.xml.txt)
[JavaException.txt](https://github.com/EXXETA/sonar-esql-plugin/files/4269035/JavaException.txt)

**Comment by ThomasPohl** [comment]
Thanks for your bug report.
Which version of SonarQube and esql-sonar-plugin were you using? 
The issue might be already fixed by version 3.0.1 of the plugin.

**Comment by RSPalazzo** [comment]
SonarQube: Version 7.9.2
esql-sonar-plugin: Version 3.0.0

I will try out version 3.0.1

**Comment by rudrakshi** [comment]
This occurs when the scan is run from java version 9 or higher

**Comment by ThomasPohl** [comment]
Then it's just because JAXB is not part of the JDK anymore. Probably I just need to add another dependency. I check on that

**Comment by ThomasPohl** [comment]
Since version 3.0.0 the jaxb dependencies are on the classpath. Otherwise the code wouldn't compile. So that was not the problem.

**Comment by ThomasPohl** [comment]
I replaced JAXB with SAX. Now it seems to work. I was not able to get JAXB or Jackson to work with the new scanner. SAX seems to work fine. And since it is part of the JDK that even decreased the size of the plugin jar.
Please check https://github.com/EXXETA/sonar-esql-plugin/releases/tag/3.0.2-RC1 as soon as the travis build is done.
