### ISSUE TITLE
Unable to scan esql file, getting null pointer exception

### ISSUE THREAD

**Issue by vipul-bhardwaj** [EXXETA/sonar-esql-plugin#118]
![image](https://user-images.githubusercontent.com/64543025/83034149-d6732980-a02f-11ea-81d2-19a4f3b645ef.png)

**Comment by vipul-bhardwaj** [comment]
Here is piece of code i have written for it.


**package com.exxeta.iss.sonar.esql.check;

import org.sonar.check.Rule;

import com.exxeta.iss.sonar.esql.api.tree.statement.DeclareStatementTree;
import com.exxeta.iss.sonar.esql.api.visitors.DoubleDispatchVisitorCheck;

@Rule(key="BlobVariableName")
public class BlobVariableNameCheck extends DoubleDispatchVisitorCheck{
	
	@Override
	public void visitDeclareStatement(DeclareStatementTree tree){
			if(tree.dataType().dataType().text().toUpperCase().equals("BLOB")) {
				for(int i=0;i<tree.nameList().size();i++) {
					if(!tree.nameList().get(i).name().startsWith("blob")) {
						addIssue(tree,"Blob Variable Name: "+tree.nameList().get(i).name()+" must start with blob");
					}
				}
			}
	}
}**

**Comment by vipul-bhardwaj** [comment]
`package com.exxeta.iss.sonar.esql.check;

import org.sonar.check.Rule;

import com.exxeta.iss.sonar.esql.api.tree.statement.DeclareStatementTree;
import com.exxeta.iss.sonar.esql.api.visitors.DoubleDispatchVisitorCheck;

@Rule(key="BlobVariableName")
public class BlobVariableNameCheck extends DoubleDispatchVisitorCheck{
	
	@Override
	public void visitDeclareStatement(DeclareStatementTree tree){
			if(tree.dataType().dataType().text().toUpperCase().equals("BLOB")) {
				for(int i=0;i<tree.nameList().size();i++) {
					if(!tree.nameList().get(i).name().startsWith("blob")) {
						addIssue(tree,"Blob Variable Name: "+tree.nameList().get(i).name()+" must start with blob");
					}
				}
			}
	}
}`

**Comment by ThomasPohl** [comment]
Hi @vipul-bhardwaj ,
can you provide the esql file or the relevant part of it? Then it should be easy to fix this issue.

**Comment by ThomasPohl** [comment]
Is BlobVariableNameCheck a rule you defined somewhere else? I think it's not part of the current codebase.

**Comment by vipul-bhardwaj** [comment]
Hi Thomas,

This issue is resolved now.
Thanks for the concern.
