### ISSUE TITLE
Question: SonarQube Community edition

### ISSUE THREAD

**Issue by manoger** [EXXETA/sonar-esql-plugin#125]
Hello.
Is there any limitation in this plugin with SonarQube Community edition?
Can I use the plugin plus the software commercially for undefined time?

**Comment by ThomasPohl** [comment]
Hello @manoger,
there are no limitations for the esql plugin. It is published under the Apache 2.0 license and there is no other version than the one published here on github. 
There are only limitations within SonarQube itself: https://www.sonarqube.org/downloads/

**Comment by manoger** [comment]
Great. I wanna use the plugin completely with the SonarQube's free version
