### ISSUE TITLE
Maven build failed

### ISSUE THREAD

**Issue by parthabaidya** [EXXETA/sonar-esql-plugin#126]
I have forked the github repository of the latest sonarqube plugin from Github. But the maven buld failed. 
Could not find out why the build has failed. Is there any other way to get the "esql-plugin-.jar"?

**Comment by ThomasPohl** [comment]
Hi @parthabaidya,

you can just download the jars right here on github: https://github.com/EXXETA/sonar-esql-plugin/tags
