### ISSUE TITLE
Not compatible with Sonarqube 9.2

### ISSUE THREAD

**Issue by kkalwaysok** [EXXETA/sonar-esql-plugin#143]
esql-plugin-2.3.5.jar not compatible with Sonarqube 9.2

**Comment by ThomasPohl** [comment]
I have created a release candidate  for SonarQube 9.2:

https://github.com/EXXETA/sonar-esql-plugin/releases/tag/3.3.0-RC3

If you find any issues, please give me feedback.

**Comment by Triodes** [comment]
Hey @ThomasPohl,
I'm currently running sonarqube 8.9 LTS, can you confirm the latest release is compatible with that?

**Comment by ThomasPohl** [comment]
Hi @Triodes ,
the release 3.3.0 will have sonarqube 8.9 as the minimum version. Since there are no reported issues with the release candidate, I will release it shortly.

**Comment by Triodes** [comment]
Thank you for confirming!

**Comment by kkalwaysok** [comment]
Hello @ThomasPohl can you create a plugin for 9.4, that one you provided is not working.
