### ISSUE TITLE
Parse errors on scanning .esql files

### ISSUE THREAD

**Issue by enjoyy2** [EXXETA/sonar-esql-plugin#150]
Every time we scan a file that contains "COMMIT;" or "ROLLBACK;" commands, the scanning fails with error:

ERROR: Parse error at line 47 column 9: 

47:   COMMIT;
                     ^
                     
Every time we scan a files that has a databaseinput node generated file by toolkit we receive parsing erros at module create definition

ERROR: Parse error at line 42 columns 16: 

42:   CREATE DATABASEEVENT MODULE ....
                                     ^

**Comment by ThomasPohl** [comment]
Hi @enjoyy2 ,
the databseevent-module is fixed and will be part of the next release. I can't find any documentation on ROLLBACK and COMMIT in the ESQL reference. Do you have the reference?

**Comment by ThomasPohl** [comment]
I finally found the problem. I had saved the declaration twice (No clue why that was no problem in previous versions) Will be fixed in next release

**Comment by ThomasPohl** [comment]
@enjoyy2 Please check if release [3.4.0-RC2](https://github.com/EXXETA/sonar-esql-plugin/releases/tag/untagged-daaa377877fb90843836) fixes the problem for you

**Comment by enjoyy2** [comment]
> Hi @enjoyy2 , the databseevent-module is fixed and will be part of the next release. I can't find any documentation on ROLLBACK and COMMIT in the ESQL reference. Do you have the reference?

there are 2 keywords that can be used in esql, commit and rollback, they act the same as the passhtru('commit'); 

i saw u fixed them, i will ask the CI/CD admin to update the plugin as i don't have that permissions in my system. 

I will post an update as soon as i manage to test it.

thanks so much ! i never believed this would be fixed :D

**Comment by ThomasPohl** [comment]
I found a small reference to COMMIT and ROLLBACK:
https://www.ibm.com/docs/en/app-connect/12.0?topic=transactions-transactional-model#ac07010_databaseauxiliarytransactions__title__1
Are you also using the UNCOORDINATED keyword in your code?

**Comment by enjoyy2** [comment]
No, so far i am not using UNCOORDINATED keyword, but i understand its utility and others might use it if they want different apps to know about each others data and progress for eg.

**Comment by ThomasPohl** [comment]
@enjoyy2 OK, then I won't handle that especially because IBM has no detailed documentation on the UNCOORDINATED keyword.

I created a new release with support for COMMIT and ROLLBACK. I hope that helps :-)
https://github.com/EXXETA/sonar-esql-plugin/releases/tag/3.5.0
