### ISSUE TITLE
compatibility with sonarqube version 9.9.7 (this should be 9.9.2)

### ISSUE THREAD

**Issue by EmreCihanbeyoglu** [EXXETA/sonar-esql-plugin#156]
Hi, 

This is an only question which is important for my setup. We have an upgrade plan for Sonarqube version 9.9.2. I couldn't find a certain information regarding compatibility. I see that it is known that version 10 cannot be used with this. Could you please let me know what about version 9.9.2 which is the latest LTS for Sonarqube. 

Kind regards
Emre

**Comment by ThomasPohl** [comment]
Hi @EmreCihanbeyoglu ,
I tested the plugin with Sonarqube 9.9.2 and I couldn't find any issue. So I'm pretty sure 9.9.7 (which I can't find on the website) will be totally fine.

Regards
Thomas

**Comment by EmreCihanbeyoglu** [comment]
Hi @ThomasPohl , 

thanks a lot for your response. It was exactly what I wanted to figure out. It was a typo. The version that I was wondering is 9.9.2. So I got the answer. :) 

Thanks a lot for the information. And sorry for inconvinience. 

Kind regards
Emre
