### ISSUE TITLE
Share any manual or documentation on how to create new esql rules.

### ISSUE THREAD

**Issue by prachithakur** [EXXETA/sonar-esql-plugin#23]
Hi,
 I am trying to create new rules, however I got stuck at the error mentioned in attached file. Please provide some guidelines about how to start with it.

Regards,
Prachi
![1](https://user-images.githubusercontent.com/33160556/32163223-9dbedd52-bd81-11e7-8f7c-395e5785e2be.PNG)

**Comment by aarjavshah** [comment]
Hi,
I just checked the FunctionNameCheckTest and it is running without any issues. Have you made any changes in the functionName.esql file? 
As per the rule functionOK() on line 8 should pass the check.

Regarding rule development, let me know what exact details you need? 

Regards,
Arjav.

**Comment by prachithakur** [comment]
Hi Arjav,

Thanks for replying.
I neee to create rule that will check that every function should start with
'FUNC_'  keyword. I did some changes in existing rule as per our
requirement and successfully run the test and compile it.But I got stuck
while deploying it. Will u help me or share some steps that how to
successfully deploy it in the existing plugin.

Thanks,
Prachi

On Wednesday, November 22, 2017, Arjav Shah <notifications@github.com>
wrote:
> Hi,
> I just checked the FunctionNameCheckTest and it is running without any
issues. Have you made any changes in the functionName.esql file?
> As per the rule functionOK() on line 8 should pass the check.
>
> Regarding rule development, let me know what exact details you need?
>
> Regards,
> Arjav.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/E35LD9lYvy5bxPf6LWfmfJ_6FlG2OF8y5MeFzviHBUepYWG59YheI7LefhFRcCjXmlldaiziB7PqLcgOMFFBYNWrOosSmKs0d0CvSbC_-Zv192bzfyyVsA1xEYDWBxoIbK5QFGorllnthgAdbmR9D72c6Vr_Mg=s0-d-e1-ft#https://github.com/notifications/beacon/Afn9bA2iyNLlRJo0RiBxIwIcoF8fgRQ5ks5s5EbygaJpZM4QK4MM.gif>

**Comment by aarjavshah** [comment]
Hi,

So, To accommodate your changes you would have updated the  pattern in the FunctionNameCheck. Accordingly you need to update the junits for the updated pattern or skip the test cases in the maven build(not recommended).

Alternatively, Do not make any code changes. You can use the custom pattern from the admin login on sonarqube as this plugin provide the customizable RuleProperties on many of the rules. PFB the snip for the reference. I would recommend using this as this would be easily configurable if you have a requirement to update this in the future. Let me know if you have more doubts.
![sonarcubeadmin](https://user-images.githubusercontent.com/20645182/33326637-83085220-d47b-11e7-9046-9380b55d007e.PNG)

**Comment by prachithakur** [comment]
Hi,

Yes, still have more doubts. While trying to make changes on web, it
doesn't show any option for change as shown below:
[image: Inline image 1]

Please correct me where I'm going wrong. And while creating the same with
coding, i got issue while deploying that 'File is not plugin'.

And apart from this, I need to create some new rules also. So, provide me
some guidelines for creating the same.

Thanks,
Prachi

**Comment by aarjavshah** [comment]
Hi Prachi,
Unable to see the screenshot. Please share it. To make this easier please fork this repository and push your changes. I'll be able to see the changes you made and help out in any way I can.

Regards,
Arjav.

**Comment by prachithakur** [comment]
Now, I have attached the screenshot.

Thanks,
Prachi

On Wednesday, November 29, 2017, Arjav Shah <notifications@github.com>
wrote:
> Hi Prachi,
> Unable to see the screenshot. Please share it. To make this easier please
fork this repository and push your changes. I'll be able to see the changes
you made and help out in any way I can.
>
> Regards,
> Arjav.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/7bk8XtDlCrqbdc47ZVEnXpZQYBh3AjYfPBB3I5DtAO6evoNu3GGXGEkG6cZ2rDoAiEPKv3aWH74q8T6ye4KTBiOzHxe6k37RjQ9AH_gvXTPFiyITFxClcqLAvahXw0JX4qb9rGmb3gncJZp6rW1S_T9EqicwwA=s0-d-e1-ft#https://github.com/notifications/beacon/Afn9bBVmAzJ_MjKzo34fBnE6XVZ9PUjSks5s7W9QgaJpZM4QK4MM.gif>

**Comment by aarjavshah** [comment]
I am still on able to see the screen shot. Please go to the issue page instead of email reply and upload the same.

**Comment by prachithakur** [comment]
Hi,

I successfully made changes to the existing rule and now that will work perfectly fine. Now, I want to create some new rules, for eg,  A single line comments should be preceded by a single blank line and immediately followed by the code that it describes.
Please share some steps or any document if you have for implementing the same as this is totally new for me.

Regards,
Prachi

**Comment by EddyVos** [comment]
Isn't it fun to search through the code and find it out yourself @prachithakur   ;-)

Looking at your message "need to create rule that will check that every function should start with
'FUNC_'  keyword" looks more like a 'personal/complany' rule then a community rule. Aarjav and his team are now working on rules that would help the community as well. Rules that we have that are personal/company bounded are we building in a separate ruleset. This way the Exetta ruleset is a clean set.

But that's just a personal thought. Maybe that @ThomasPohl could advice you more in this :-)

**Comment by aarjavshah** [comment]
We do not have any such documentation to guide for the new rule creation (Thomas and EXXETA folks might have something), but you can refer to the implementation of the currently available rules and take it up from there.

**Comment by ThomasPohl** [comment]
I don't have any specific documentation on esql rules either.
Referring to the existing rules and their JUnit-Tests will hopefully help you a little more. You might also have a look at the JavaScript Plugin https://github.com/SonarSource/SonarJS. The structure of that plugin is very similar to the ESQL plugin.
There is an extension guide from sonarqube: https://docs.sonarqube.org/display/DEV

**Comment by prachithakur** [comment]
Ok, thanks a lot.

**Comment by aarjavshah** [comment]
@prachithakur Refer https://github.com/EXXETA/sonar-esql-plugin/wiki#requirements-for-new-checks for the addition of new rules.
@ThomasPohl has added the basic steps for rule addition.

**Comment by gabrielkalb** [comment]
I Have created a documentation step-by-step on how to create a new rule:

[https://github.com/EXXETA/sonar-esql-plugin/wiki/How-to-create-a-new-rule-in-SonarESQLPlugin](url)

**Comment by ThomasPohl** [comment]
What a great and detailed documentation. Thanks a lot!
