### ISSUE TITLE
Redundant checks

### ISSUE THREAD

**Issue by ThomasPohl** [EXXETA/sonar-esql-plugin#25]
It seems that there are a few checks that implement the same semantic:

- SpaceAroundEqualSignCheck could be replaced by BinaryOperatorSepratedBySpaceCheck
- CaseStatementWithSingleWhenCheck could be replaced by CaseAtLeastThreeWhenCheck
- EXTERNALVariableInitialisedCheck implements the same logic as InitializeVariablesCheck
- AvoidNestedIfCheck could be replaced by NestedIfDepthCheck
- MeaningfulVariableCheck could be replaced by VariableNameCheck
- MessageDomainNotvalidCheck could be replaced by UnknownMessageDomainCheck
- DepricatedMethodCheck could be replaced by BitstreamCheck
- FileHeaderCommentsCheck could be replaced by FileHeaderCheck

@aarjavshah  and @EddyVos maybe I have overlooked something. Please verify if these rules are really redundant.

**Comment by aarjavshah** [comment]
@ThomasPohl I'm checking this. I'll verify and confirm.

**Comment by ThomasPohl** [comment]
@aarjavshah any news on this?

**Comment by sapna392** [comment]
Hi Thomas,
Details are as below:

- BinaryOperatorSepratedBySpaceCheck will be used we can remove SpaceAroundEqualSignCheck
- CaseAtLeastThreeWhenCheck  will be used
- InitializeVariablesCheck  will be used
- NestedIfDepthCheck  will be used
- VariableNameCheck  will be used 
- UnknownMessageDomainCheck  will be used
- DepricatedMethodCheck(new) could be replaced by BitstreamCheck(existing) 

BitstreamCheck(existing) - it is only for BITSTREAM, need to create check files for each function; we have externalised the function name list .So DepricatedMethodCheck(new) will be better option.

**Comment by ThomasPohl** [comment]
Hi @sapna392 ,
thanks for your feedback.
I will remove the redundant checks.

For BitstreamCheck <->DepricatedMethodCheck:
I see the benefits of a configurable list with deprecated methods. The issue I see with the current implementation of DepricatedMethodCheck is that it just looks for a string within the esql file. No matter if it is just a substring of a variable name or within a comment. So it can produce a lot of false positives. 
I could change the implementation to use a SubscriptionVisitorCheck and save a list of node-Kinds containing the deprecated methods. But that way we would loose some flexibility. 
Would such a check still meet you requirements?

**Comment by ThomasPohl** [comment]
@sapna392 
I just noticed that you didn't say anything about FileHeaderCommentsCheck vs FileHeaderCheck. Any thoughts on that?

**Comment by sapna392** [comment]
Hi Thomas ,

we need to keep the FileHeaderCommentsCheck  as well because we are checking header comments in specific format as per our requirement hence we can not use the existing FileHeaderCheck as it is .

**Comment by ThomasPohl** [comment]
Have you tried to use a regex for example like this:
\/\*\r?\nChange Log\r?\nNo. Incident Number  Jira Number  Description  Date Fixed  Updated ESQL/Node.*\r?\n\*\/

The FileHeaderCommentsCheck is very specific for your needs and is not a generic solution for everyone. I always try to find more generic solution.

**Comment by EddyVos** [comment]
@sapna392 I agree with Thomas. Let's have a chat tomorrow. Ping me when you see me online!

**Comment by ThomasPohl** [comment]
@sapna392 @EddyVos : Did you come to an an conclusion? I have added an example of your header syntax to the FileHeaderCheckTest.java.

**Comment by sapna392** [comment]
Hi @ThomasPohl 
We have checked FileHeaderCheckTest.java , and this is working for us , so we can replace FileHeaderCommentsCheck with FileHeaderCheck.

Thanks for the test case
