### ISSUE TITLE
IllegalArgumentException for CyclomaticComplexity

### ISSUE THREAD

**Issue by sapna392** [EXXETA/sonar-esql-plugin#33]
Hi Thomas
We are getting
"Caused by: java.lang.IllegalArgumentException: Rule 'esql:CyclomaticComplexity' can not use 'Constant/issue' remediation function because this rule does not have a fixed remediation cost.
"Due to which we are not able to genertate report.

In  CyclomaticComplexity.json ,
 if we remove

"remediation": {
    "func": "Constant\/Issue",
    "constantCost": "45min"
  },

we don't get that issue.

**Comment by ThomasPohl** [comment]
Hi Sapna,

the CyclomaticComplexity.json ("constantCost") didn't fit to the variable cost in CyclomaticComplexityCheck. I fixed like you suggested.
Thanks for the bug report.
