### ISSUE TITLE
MultipleStatementsCheck 

### ISSUE THREAD

**Issue by ThomasPohl** [EXXETA/sonar-esql-plugin#36]
add an parameter to the OneStatementPerLineCheck to only check for SET statements, so that the user can choose if he wants only to prevent multiple set statements on the same line.

@preranaagarkar1 Is that what you wanted to accomplish with MultipleStatementsCheck?

**Comment by preranaagarkar1** [comment]
Hi Thomas,

Yes in MultipleStatementsCheck Rule, SET,CREATE,etc. statements if present on the same line, it will throw issue. And also it will throw issue for two or more SET statements on the same line.

**Comment by ThomasPohl** [comment]
Hi @preranaagarkar1 ,

finally I understood what the problem is. Actually the OneStatementPerLineCheck was supposed to to exactly what you are describing, but there is a bug in the implementation. I will fix that and merge both Checks.
