### ISSUE TITLE
Parsing error in ESQL file

### ISSUE THREAD

**Issue by mcarajatchawla** [EXXETA/sonar-esql-plugin#4]
14:39:43.889 [main] ERROR org.sonar.squidbridge.AstScanner - Unable to parse file: 
14:39:43.889 [main] ERROR org.sonar.squidbridge.AstScanner - Parse error at line 312 column 54:

  310: ns36  NAME 'eventPayLoad';
  311:    CREATE FIELD outRef.ns36:eventPayLoad  FROM payRef.*:eventPayLoad;
  -->     SET outRef.ns36:eventPayLoad.(XMLNSC.NamespaceDecl)=NULL;
  313:    CALL StripNamespaces(outRef.ns36:eventPayLoad);
  314:  END;
  315: END MODULE;EOF

**Comment by ThomasPohl** [comment]
SET outRef.ns36:eventPayLoad.(XMLNSC.NamespaceDecl)=NULL;

This syntax is actually not valid according to the IBM documentation. 
http://www-01.ibm.com/support/knowledgecenter/SSMKHH_9.0.0/com.ibm.etools.mft.doc/ac67194_.htm?lang=en

Although the IIB-parser probably accepts it.

The valid syntax would be:
SET outRef.ns36:eventPayLoad.(XMLNSC.NamespaceDecl)*=NULL;

After this change both parsers (IIB an esql-sonar-plugin) should be able to parse the code.

**Comment by ThomasPohl** [comment]
With version 2.0.0 the plugin will support statements like the one you wanted to parse.
