### ISSUE TITLE
Include BinaryOperatorSepratedBySpaceCheck

### ISSUE THREAD

**Issue by sapna392** [EXXETA/sonar-esql-plugin#42]
Hi Thomas ,

please merge BinaryOperatorSepratedBySpaceCheck .

**Comment by ThomasPohl** [comment]
I'm sorry. I included SpaceAroundEqualSignCheck and removed BinaryOperatorSepratedBySpaceCheck . I will fix that.

**Comment by ThomasPohl** [comment]
I added the BinaryOperatorSepratedBySpaceCheck which replaces SpaceAroundEqualSignCheck. I will think about creating an abstract class with the logic for spaces before or after an punctuator and two concrete implementation one for binary operators and one for commas. 
That way there is one place for the logic but the user can decide which rules he wants to include and which not.
