### ISSUE TITLE
FilterNodeHaveOnlyOneReturnCheck throwing issue when there is no filter node in esql file

### ISSUE THREAD

**Issue by sapna392** [EXXETA/sonar-esql-plugin#43]
Hi Thomas ,
FilterNodeHaveOnlyOneReturnCheck is throwing issue in those files also in which there is no filter module.

**Comment by ThomasPohl** [comment]
I found the problem and I will fix it, but I am really not sure about the logic of this check:
Currently there are three cases in which an issue is created:
- no return or throw
- only false return or throw
- only true return

Why is return false and throw treated the same way? They have different output [terminals](https://www.ibm.com/support/knowledgecenter/en/SSMKHH_9.0.0/com.ibm.etools.mft.doc/ac04780_.htm).
There could always happen an exception in the database or any called function or procedure which we cannot recognize. Which would also be a different result.

What is your opinion on that?
