### ISSUE TITLE
several findings

### ISSUE THREAD

**Issue by MichaelGutbrod** [EXXETA/sonar-esql-plugin#5]
Hey,

we use the plugin and found several errors during the run of the plugin in Jenkins console.

Could you please verify them.
*************************
12:12:37.253 ERROR - Parse error at line 108 column 42:

  104: ) AS CHAR CCSID 819);
  105: 
  106:   CREATE FIELD Environment.Variables.SapIdocControlHeader as refControlRecord_;
  107:   SET refControlRecord_ = ROW(
  -->     TRIM(SUBSTRING(cIdocHeader FROM 19 FOR 3))   AS LogicalMessageCode ,
  109:    TRIM(SUBSTRING(cIdocHeader FROM 163 FOR 10)) AS PartnerNumberOfSender,
  110:    TRIM(SUBSTRING(cIdocHeader FROM 100 FOR 30)
*************************
12:12:37.257 ERROR - Parse error at line 3 column 73:

    1: .filein
    2: 
  -->  PATH com.pag.eai.common, com.pag.eai.common.cs, com.pag.eai.common.logger;
    4: DECLARE bo_IsFTP EXTERNAL BOOLEAN FALSE;
    5: 
    6: CREATE COMPUTE MODULE Common_In_FileIn_PrepareRead
   
*************************
10:29:33.482 ERROR - Parse error at line 392 column 37:

  386: ) RETURNS BLOB
  387:  BEGIN
  388:   DECLARE blResult BLOB;
  389: 
  390:   IF ((blReplChar IS NULL) OR (blReplChar = '' )) THEN
  391: 
  -->     SET blResult = TRANSLATE(blSource,x'00');
  393:    SET blResult = TRANSLATE(blResult,x'01');
  394:    SET blResult = TRANSLATE(blResult,x'02');
  395:    SET blResult = TRANSLATE
*************************
16:07:41.349 ERROR - Parse error at line 13 column 37:

   10:   DECLARE rowResult ROW;
   11: 
   12: 
  -->     SET rowResult.result[] = PASSTHRU('UPDATE EAI_SST.INTERFACE_DATA SET EAI_KEY = ?, EAI_VALUE = ? WHERE INTERFACE_NR = ?' VALUES('S', Environment.Variables.lastChangeId, '22202' ));
   14: 
   15:   CALL com.pag.eai.common.logger.Info(Environment
*************************
16:07:41.352 ERROR - Parse error at line 18 column 36:
   15: 
   16:   DECLARE rowResult ROW;
   17:   DECLARE cID CHAR;
  -->    SET rowResult.result[] = PASSTHRU('SELECT EAI_KEY, EAI_VALUE FROM EAI_SST.INTERFACE_DATA AS IFDATA WHERE IFDATA.INTERFACE_NR = ?' VALUES(12345));
   19: 
   20:   IF rowResult.result.EAI_KEY <> 'S' THEN
   21: 
   22:    CALL com.pag.eai.common.logger.Info(Environment

*************************
16:46:04.852 ERROR - Parse error at line 64 column 64:
   61: 
   62: 
   63:     SET rowSQLReturnLines = PASSTHRU ('SELECT Status_xx, Status_yy
  -->                                         FROM ' || Environment.Variables.yy_Schema || '.PRODAP_Zugriff
   65:                                        WHERE Tab_Name = ?'
   66:               VALUES (refTablename));
   67: 
   68: 
   69:     SET cEaiLockStatus = COALESCE(rowSQLReturnLines.Status_Fremdsystem, '');
   70:     SET cProdapLockStatus = COALESCE(rowSQLReturnLines.Status_yy, '')
*************************
16:46:04.863 ERROR - Parse error at line 25 column 10:

   23:   IF refUpdateTrigger.Interface = 'qq' THEN
   24:    PASSTHRU 'UPDATE ' || EAI_Schema || '.SST_xxx SET DELIVERED_PSI = ?, DATE_MODIFIED = ? WHERE INTERFACE = ? AND TRIGGER_ID = ?'
  -->      VALUES('X', CURRENT_TIMESTAMP, 'xxx', refUpdateTrigger.TriggerId);
   26:   ELSE
*************************
16:46:04.871 ERROR - Parse error at line 78 column 56:

   76: .logger.Debug(Environment, 'Schreibe Block ' || CAST(iBlockCounter AS CHAR) || ' nach SST_EAI');
   77: 
  -->      SET Environment.Variables.insertState[] = PASSTHRU (chSQLStmt VALUES (refEnvInsertValues.col[]));
   79:     CALL com.eai.common.logger.Debug(Environment, 'Block ' || CAST(

*************************16:37:55.129 ERROR - Parse error at line 6 column 14:

    4:   DECLARE rowResult ROW;
    5:   SET rowResult.result[]
  -->     = PASSTHRU('UPDATE x.GSD SET ABZUG_STATUS = ? WHERE MJ_4 = ? AND BTYP = ? AND GG_ID = ? AND SPR_CD = ? AND SYSTEM = ?'
    7:      VALUES('T', refEnvironment.Variables.MJ_4, refEnvironment.Variables.BTYP, refEnvironment.Variables.GG_ID, refEnvironment.Variables.SPR_CD, 'xx'

*************************
16:37:55.132 ERROR - Parse error at line 23 column 36:

   21: 
   22:   DECLARE rowResult ROW;
  -->    SET rowResult.result[] = PASSTHRU('SELECT a, b, GG, SPR FROM yyy.xx AS BTYP WHERE BTYP.xx = ? AND BTYP.Sxxx = ?' VALUES('A', '1417'));
   24: 
   25: 
*************************
16:37:55.137 ERROR - Parse error at line 7 column 23:

  -->  PATH com.pag.eai.common;
    8: 
    9: DECLARE rowResult_ SHARED ROW NULL;
*************************
13:01:44.139 ERROR - Parse error at line 49 column 72:

   48:    CREATE LASTCHILD OF rowBlock.InsertValues AS refCol NAME 'col' VALUE formatDBCharValue(refFileRecord.xxx.yy_1);
  -->     CREATE NEXTSIBLING OF refCol AS refCol REPEAT VALUE formatDBCharValue(refFileRecord.xxx.yy_2);

*************************
22:09:46.902 ERROR - Parse error at line 16 column 21:

  
   15:   DECLARE refFileRecord REFERENCE TO Root.DFDL.xx.Record;
  -->    DECLARE dAlertDate DATE '1970-01-01';
   17:   DECLARE dPlnDate DATE '1970-01-01';
   18:   DECLARE strPattern CHARACTER 'yyyyMMdd';
  
*************************

**Comment by ThomasPohl** [comment]
All these findings are fixed with the Version 1.0.1.
