### ISSUE TITLE
Issue with UnusedVariableCheck 

### ISSUE THREAD

**Issue by sapna392** [EXXETA/sonar-esql-plugin#51]
Hi Thomas ,

we are facing an issue with UnusedVariableCheck,

for this 
addIssue(new LineIssue(this, tree, "Check Variable \"" + Variabl + "\". " + MESSAGE));
if a issue was thrown in one file for the unused variable, 
again we will get issue in another file with the same variable name , even though that variable is not declared or used in that file.
Also if we use 
addIssue(new PreciseIssue(this, new IssueLocation(variable.getValue(),variable.getValue(), String.format(MESSAGE, variable.getKey()))));
then we will get error
Caused by: java.lang.IllegalArgumentException: 61 is not a valid line offset for
 pointer. 
can you suggest which issue we can use in this case,

**Comment by ThomasPohl** [comment]
@sapna392 
Can you verify my fix. I had the same issue and for me these changes solved it.

**Comment by sapna392** [comment]
@ThomasPohl 

Thanks , issue got fixed.
