### ISSUE TITLE
DeleteFromWithoutWhereCheckTest » NullPointer Exception

### ISSUE THREAD

**Issue by sapna392** [EXXETA/sonar-esql-plugin#52]
Hi Thomas ,

We are getting null pointer exception in DeleteFromWithoutWhereCheck

**Comment by ThomasPohl** [comment]
Hi Sapna, 
Thanks for the report. Can you give me an example ESQL and the stack trace?

**Comment by sapna392** [comment]
We are getting NPE for the same esql which you have used in the exxeta.

CREATE COMPUTE MODULE a

	CREATE PROCEDURE delete()
	BEGIN
		DELETE FROM Database.SHAREHOLDINGS; --Noncompliant
		DELETE FROM Database.SHAREHOLDINGS AS S; --Noncompliant
		DELETE FROM Database.SHAREHOLDINGS AS S WHERE S.ACCOUNTNO = InputBody.AccountNumber; --Compliant
		PASSTHRU('DELETE FROM users'); --Noncompliant
		PASSTHRU 'DELETE FROM users'; --Noncompliant
		PASSTHRU(('DELETE FROM users')); --Noncompliant
		PASSTHRU(('DELETE FROM users WHERE NAME=''name''')); --Ccompliant
		PASSTHRU(STMT); --Compliant
		PASSTHRU('SELECT * FROM dual'); --Compliant
	END;

END MODULE;

**Comment by ThomasPohl** [comment]
@Sapna did you recompile the esql-frontend module? I changed skipParentheses method in the class SyntacticEquivalence. 
If you get the NPE when you are running the DeleteFromWithoutWhereCheckTest, the problem is probably on your side. The travis build runs without any issues.

**Comment by sapna392** [comment]
@ThomasPohl  thanks, its working now.
