### ISSUE TITLE
Use SymbolModel for UnusedVariableCheck

### ISSUE THREAD

**Issue by ThomasPohl** [EXXETA/sonar-esql-plugin#53]
@sapna392 
I think instead of parsing the ESQL code again in the UnusedVariableCheck, it would be easier to use the SymbolModel. It could be something like this:

	@Override
	public void visitProgram(ProgramTree tree) {
		super.visitProgram(tree);
		SymbolModel symbolModel = getContext().getSymbolModel();
		for (Symbol symbol : symbolModel.getSymbols()) {

			Collection<Usage> usages = symbol.usages();
			if (noUsages(usages)) {
				if (symbol.isVariable()) {
					raiseIssuesOnDeclarations(symbol, String.format(MESSAGE, symbol.name()));
				}
			}
		}
	}

	private void raiseIssuesOnDeclarations(Symbol symbol, String message) {
		for (Usage usage : symbol.usages()) {
			if (usage.isDeclaration()) {
				addIssue(usage.identifierTree(), message);
			}
		}
	}

	private static boolean noUsages(Collection<Usage> usages) {
		return usages.isEmpty() || usagesAreInitializations(usages);
	}

	private static boolean usagesAreInitializations(Collection<Usage> usages) {
		for (Usage usage : usages) {
			if (!usage.isDeclaration()) {
				return false;
			}
		}
		return true;
	}

**Comment by sapna392** [comment]
@ThomasPohl  thanks for this implementation , we can add this .
