### ISSUE TITLE
Issues with PropagateConsistencyCheck

### ISSUE THREAD

**Issue by aarjavshah** [EXXETA/sonar-esql-plugin#55]
False positive issues are thrown for the terminals which are connected in the message flow.
Reason : Line 148 : 
**String target = expression.toString();**
This returns the target value with single quote eg. _'out1'_. This results into checking for _OutTerminal.'out1'_ in the list of output terminals for the node, which will be false as the value present would be _OutTerminal.out1_. This behaviour will not replicate for terminal 'out' as it is not looked up using getTerminalName() mehod.
Solution : changing return statement of the above method.
****return target.replace("'", "");****

**Comment by aarjavshah** [comment]
@ThomasPohl There is one more issue in this. The relative path of esqlFile that is used to identify the project directory is causing issues which running it on actual projects. I've identified the fix. I will test and confirm if it works as expected.

**Comment by ThomasPohl** [comment]
@aarjavshah can you explain how I can reproduce the issue you have found? Is there a commit with your fix?

**Comment by aarjavshah** [comment]
@ThomasPohl I ran the sonar analysis on a simple project with sonar-scanner, where I had a statement in the esql propagating to the terminal which is not connected in the message flow. 
The issue wasn't detected in the analysis. When I did some debugging, found out that the file object was set to null. So, no message flow was detected. 
**File projectDirectory = getProjectDirectory(esqlFile);**

About the solution part, PFB the link to an earlier version of the file I was mentioning.
https://github.com/EXXETA/sonar-esql-plugin/blob/b6d156b5fbc5176c9bc902fa353a7310bb97cee8/esql-frontend/src/main/java/com/exxeta/iss/sonar/esql/api/visitors/TreeVisitorContext.java

**Comment by ThomasPohl** [comment]
I tried to reproduce your issue, but I didn't succeed. Can you check if there is a .project file in your project directory?

**Comment by aarjavshah** [comment]
Yes, there is a .project file in the directory. However, I'll upload the sample IIB project for which I had that issue today. 
Try checking this for the projectDirectory = null. It will go in the execution of the if part. 
`if (new File(projectDirectory, ".project").exists()) {`

One more thing, when you ran the sonar analysis to reproduce this issue, did you get the code smell for this rule?

**Comment by aarjavshah** [comment]
@ThomasPohl 
I've pushed the code in the below repository. I'm using the sonar-scanner.bat for the sonar analysis. I also tried to run the sonar analysis using the maven build on IIB maven project.

https://github.com/aarjavshah/SonarTestProject

For the solution point of view, we should use the absolute path of the esql file so we can get the absolute path of the project directory and that will return the proper list of the message Flows in the project directory.
See the difference in the below interface in the current and the earlier code.


**Current code:**
`public interface TreeVisitorContext {
	
	
	  ProgramTree getTopTree();

	  EsqlFile getEsqlFile();

	  SymbolModel getSymbolModel();
	  
}`


**Code earlier:**
`public interface TreeVisitorContext {
	
	
	  ProgramTree getTopTree();

	  EsqlFile getEsqlFile();

	  SymbolModel getSymbolModel();
	  
	  File getFile();

}`


We can use the File object to get the absolute path instead of retrieving the relative path from the EsqlFile object. Let me know if you need any more information for the replication of this issue.

**Comment by ThomasPohl** [comment]
@aarjavshah Thanks for your sample project. I was able to reproduce the problem and I committed a fix to the release branch and the develop branch. Please verify if the problem still exists on your side.

**Comment by aarjavshah** [comment]
@ThomasPohl I'll verify and update.

**Comment by ThomasPohl** [comment]
@aarjavshah If the problem still exists, please open a new issue.
