### ISSUE TITLE
Unknown domain "ComIbmAggregateReplyBody".

### ISSUE THREAD

**Issue by npsferreira** [EXXETA/sonar-esql-plugin#63]
Hi, 

I´ve got the issue but looking at the IBM documentation it seems that this is a false positive.
Example of use:

DECLARE refData REFERENCE TO InputRoot.ComIbmAggregateReplyBody.AccDocumentPost;

Another issue that i don't find in anywhere is how we can bypass this false positive in the plugin?

Cheers, 

Bigster

**Comment by ThomasPohl** [comment]
Hi,
Thanks for the bug report. I think you are right. I will add ComIbmAggregateReplyBody to the allowed domains. 
Thomas

**Comment by aarjavshah** [comment]
@npsferreira for the issue marking as false positive you can use the sonarqube portal.
