### ISSUE TITLE
Null pointer Exeption in DeleteFromWithoutWhereCheck

### ISSUE THREAD

**Issue by sapna392** [EXXETA/sonar-esql-plugin#65]
@ThomasPohl 

We are getting NPE in DeleteFromWithoutWhereCheck at line 46 
FIX for this 
please add this condition 
else if (null != tree.expressionList() && tree.expressionList().parameters().size() != 0 && SyntacticEquivalence
				.skipParentheses(tree.expressionList().parameters().get(0)) instanceof LiteralTree) {

**Comment by ThomasPohl** [comment]
Hi @sapna392 
Can you provide the statement that causes the NPE?
