### ISSUE TITLE
Unable to Parse PASSTHRU

### ISSUE THREAD

**Issue by hitjay2002** [EXXETA/sonar-esql-plugin#66]
Hi,

We have complex DB functions and there is a need to use PASSTHRU. Plugin is unable to parse PASSTHRU of IIB 10. Would be of great help, if this can be fixed

**Comment by ThomasPohl** [comment]
Hi @hitjay2002 ,

can you provide an ESQL statement that causes the PASSTHRU parsing issue?

**Comment by hitjay2002** [comment]
I can provide the construct but not the actual code.

**Comment by ThomasPohl** [comment]
That's OK for me. Just reduce your example to a statement, that still produces the issue but doesn't contain any secret information.

**Comment by hitjay2002** [comment]
ERROR: Parse error at the place indicated with an arrow.

SET Recordgroup.Record[] = PASSTHRU('SELECT column1,column2 FROM '||db_schema||'.table_name WHERE column3=? AND column4=?' VALUES('value1',value2));
                                                 ^
