### ISSUE TITLE
Keywords list needs to be updated

### ISSUE THREAD

**Issue by rudrakshi** [EXXETA/sonar-esql-plugin#74]
KeyWordCaseCheck gives error for many keywords like list, Environment, parent, count. 
The IIB toolkit allows to create variables with these names. 
Also it does not recognize Environment as environment if it is in Uppercase.

**Comment by ThomasPohl** [comment]
Hi rudrakshi,
thanks for all your bug reports.
I have fixed the error for nonreserved keywords used as variable names. But I am not sure about the recognition of Environments. Can you add an snippet causing the issue?

**Comment by rudrakshi** [comment]
![image](https://user-images.githubusercontent.com/3128446/36210058-c3e317e4-119d-11e8-9017-f8839410449b.png)
This rule wants "Environment" should be in upper case.
But When Environment is made uppercase it is not recognized as environment in the toolkit:
![image](https://user-images.githubusercontent.com/3128446/36210393-9685429e-119e-11e8-8d9e-a0583bbe544b.png)

**Comment by ThomasPohl** [comment]
Ok , that should be covered by my changes. I will add this constellation to the testcases.
