### ISSUE TITLE
PassThruStatementCheck does not work as expected

### ISSUE THREAD

**Issue by rudrakshi** [EXXETA/sonar-esql-plugin#75]
It should check ? in where conditions.'
For example following statement should give error:
SET resultSet.rowReference[]=PASSTHRU('SELECT * FROM '||table||'.ABC A,'||table||'.BCD B,'||table||'.CDE C
 WHERE A.IDENT = '||Ident||'
 AND B.ID_NUMBER = '||inRef.xyz.value||'
 AND B.ID_NUMBER = A.ID_NUMBER
 AND C.IDENT = '||Ident||'
 AND B.DATE_MODIFIED < C.DATE' TO Database.{DB});

**Comment by ThomasPohl** [comment]
Hi @rudrakshi ,

I agree, that the PassThruStamentCheck should probably raise an issue when parsing the statement you provided. Right now the parsing algorithm for the SQL is pretty basic and only works if the passthru parameter is a plain string. 
Especially when  concatenating strings it's hard to tell what the executed statement will be. E.g. Would it be a valid if the concatenated variables would have the value '?' ?

I will look if I find a generic solution.

**Comment by rudrakshi** [comment]
@ThomasPohl I think the fix is not merged in the latest release. It still does not give error on following query:
SET resultSet.rowReference[]=PASSTHRU('SELECT * FROM '||table||'.ABC A,'||table||'.BCD B,'||table||'.CDE C
 WHERE A.IDENT = '||Ident||'
 AND B.ID_NUMBER = '||inRef.xyz.value||'
AND B.ID_NUMBER = A.ID_NUMBER
 AND C.IDENT = '||Ident||'
 AND B.DATE_MODIFIED < C.DATE' TO Database.{DB});

**Comment by ThomasPohl** [comment]
I will check that.

**Comment by ThomasPohl** [comment]
I can't reproduce this problem. When I add your code in a test-project the plugin has two findings for this passthru statement. The missing '?' and the *:
![image](https://user-images.githubusercontent.com/11629283/37202010-a433650e-2389-11e8-9200-c882d0817418.png)

**Comment by rudrakshi** [comment]
@ThomasPohl it works for parameters which are numbers but for fields which are character and are surrounded by quotes it does not recognize.
SET resultSet.rowReference[]=PASSTHRU('SELECT * FROM '||table||'.ABC A,'||table||'.BCD B,'||table||'.CDE C
WHERE A.IDENT = '''||Ident||'''
' TO Database.{DB});

**Comment by ThomasPohl** [comment]
@rudrakshi I'm still not sure what should be different. When I let sonar analyze your statements (with and without quotes) it finds the same issues:
![image](https://user-images.githubusercontent.com/11629283/37250378-82a13e98-24fb-11e8-96c6-bfa947ffa71b.png)

**Comment by ThomasPohl** [comment]
Please reopen the issue if there is still an error.
