### ISSUE TITLE
DeleteFromWithoutWhereCheck not working as expected

### ISSUE THREAD

**Issue by rudrakshi** [EXXETA/sonar-esql-plugin#76]
Follwoing delete statements will delete complete table's data:
SET resultSet.rowReference[] = PASSTHRU('DELETE FROM ABC A' TO Database.{dsDB});
SET resultSet.rowReference[] = PASSTHRU('DELETE FROM '||db2_table||'.ABC A' TO Database.{dsDB});

**Comment by ThomasPohl** [comment]
@rudrakshi thanks for reporting
@gabrielkalb thanks for fixing
I have changed your fix a little to make it more generic. Now it works for all passthruFunctions not only the ones used in setStatements.
