### ISSUE TITLE
Fail to parse DECLARE with CASE IN

### ISSUE THREAD

**Issue by gabrielkalb** [EXXETA/sonar-esql-plugin#78]
Thomas,

The code below fail to be parsed by sonar:

                                                   `DECLARE var CHARACTER 
							CASE field IN('1','2','3', '4', '5', '6') 
							WHEN TRUE THEN 
								REPLACE(field, '.',',')  
							ELSE 
								field
							END;`

Error message:
ERROR: Unable to parse file
ERROR: Parse error at line

Thanks

**Comment by ThomasPohl** [comment]
@gabrielkalb 
there was a bug when parsing CaseFunctions. It should be fixed now.
