### ISSUE TITLE
Failed while parsing "DECLARE a NAMESPACE FIELDNAMESPACE(InputRoot.XMLNSC.(XML.Element)[1]);"

### ISSUE THREAD

**Issue by desmond27** [EXXETA/sonar-esql-plugin#79]
The errors thrown are:
ERROR: Unable to parse file:
ERROR: Parse error at line

The parse error marker (^) is on the '[' in the below line.

`DECLARE a NAMESPACE FIELDNAMESPACE(InputRoot.XMLNSC.(XML.Element)[1]);`

I am positive that the above line is valid and functional since this has been observed to work in numerous tests. However, I am unable to scan my code base because sonar scanner is unable to proceed because of this one line.

**Comment by ThomasPohl** [comment]
@desmond27  Thanks for reporting. IBM allows a lot more for FieldReferences than their documentation does...

**Comment by desmond27** [comment]
This was fixed pretty quick. I really appreciate your efforts.
