### ISSUE TITLE
Functions  with the name "Main" must be accepted.

### ISSUE THREAD

**Issue by ThomasPohl** [EXXETA/sonar-esql-plugin#8]

**Comment by ThomasPohl** [comment]
Will be fixed in Version 2.0.0

**Comment by muthukumar-m** [comment]
Can i have the download link for the version 2.0.0

**Comment by ThomasPohl** [comment]
@muthukumar-m Hi, all releases are listed here: https://github.com/EXXETA/sonar-esql-plugin/releases
The download link for the latest version 2.1.1 is https://github.com/EXXETA/sonar-esql-plugin/releases/download/2.1.1/esql-plugin-2.1.1.jar
