### ISSUE TITLE
Unable parse ESQL file with CREATE FILTER MODULE when name is in double quotes

### ISSUE THREAD

**Issue by t603** [EXXETA/sonar-esql-plugin#81]
Hello!

I got another error during the scan. I am using sonarqube-6.7.1\bin\windows-x86-64 and sonar-scanner-cli-3.0.3.778-windows.

The error of very simplified ESQL is: 

```
ERROR: Unable to parse file: file:///C:/temp/temp/error02/Test.esql
ERROR: Parse error at line 1 column 22:

1: CREATE FILTER MODULE "TEST"
                        ^
2:   CREATE FUNCTION main() RETURNS BOOLEAN
3:     BEGIN
4:       RETURN (TEST_A='01') and TEST_B is null;
5:     END;
6: END MODULE;
7:
```

When I remove double quotes around the name of filter module, Sonar works OK. I guess, that surrounding of name of filter module is not prohibited, because the code was generated by IIB Toolkit (unknown version for me now). 

Regards, Stepan

**Comment by ThomasPohl** [comment]
@t603 I noticed IBM allows these double quotes also for function and parameter names. I will fix that in the parser. Thanks for reporting.
