### ISSUE TITLE
Unable parse ESQL file with SET MyVar.{'Content-' ||'Type'} = 'text/xml'; code

### ISSUE THREAD

**Issue by t603** [EXXETA/sonar-esql-plugin#82]
Hello, 

I have found another problem when parsing ESQL file. The code is: 

```
CREATE COMPUTE MODULE Test
	CREATE FUNCTION Main() RETURNS BOOLEAN
	BEGIN
		SET MyVar.{'Content-' ||'Type'} = 'text/xml';
		RETURN TRUE;
	END;
END MODULE;

```
And the reported error is: 

```
ERROR: Unable to parse file: file:///C:/temp/temp/error04/Test.esql
ERROR: Parse error at line 4 column 35:

1: CREATE COMPUTE MODULE Test
2:  CREATE FUNCTION Main() RETURNS BOOLEAN
3:  BEGIN
4:   SET MyVar.{'Content-' ||'Type'} = 'text/xml';
                                     ^
5:   RETURN TRUE;
6:  END;
7: END MODULE;
8:

INFO: 1/1 source files have been analyzed
```

I hope, that the above ESQL code is OK. May I ask You for investigation? Otherwise, this plugin looks great! 

Regards, Stepan

**Comment by ThomasPohl** [comment]
Stepan,
it was a small bug in the esql grammar. I fixed it and it will be included in the next (bugfix) release.

**Comment by t603** [comment]
Thomas, thank You very much for all Your fast resolved issues! Regards, Stepan, Prague
