### ISSUE TITLE
Unable parse ESQL file with CREATE COMPUTE MODULE when name is in double quotes

### ISSUE THREAD

**Issue by t603** [EXXETA/sonar-esql-plugin#84]
Hi, Thomas, 

one more quotes, now for CREATE COMPUTE MODULE. Running "esql-plugin-2.3.1.jar". 

The code is: 

```
CREATE COMPUTE MODULE "MY TEST"
  CREATE FUNCTION main() RETURNS BOOLEAN 
    BEGIN
      RETURN true;
    END;
END MODULE;

```
The error is: 

```
ERROR: Unable to parse file: file:///C:/temp/temp/error06/Test.esql
ERROR: Parse error at line 1 column 23:

1: CREATE COMPUTE MODULE "MY TEST"
                         ^
2:   CREATE FUNCTION main() RETURNS BOOLEAN
3:     BEGIN
4:       RETURN true;
5:     END;
6: END MODULE;
7:

INFO: 1/1 source files have been analyzed
```

Thank You very much in advance. Regards, Stepan

**Comment by ThomasPohl** [comment]
Hi Stepan,
you are right thats another bug. This only happens when there are quoted whitespaces.

**Comment by ThomasPohl** [comment]
For now I added the normal space to the regular expression. I'm not sure if other unicode whitespaces are allowed by esql.
