### ISSUE TITLE
SonarQube 5.6 L.T.S.

### ISSUE THREAD

**Issue by brunopenso** [EXXETA/sonar-esql-plugin#9]
HI it is not working with SonarQube 5.6 L.T.S.

The error is Caused by: java.lang.ClassNotFoundException: org.sonar.api.resources.ProjectFileSystem.

 I will try to fix and make a pull request!

Thanks

**Comment by ThomasPohl** [comment]
Great! Maybe you'll find an easy solution. I didn't... :-) 
I would appreciate any pull requests.

**Comment by ThomasPohl** [comment]
I started to migrate the plugin to the current SonarQube API. At the moment I can't tell when it will be done.

**Comment by EddyVos** [comment]
Hi Thomas, did you manage to implement the latest SonarQube API in the project?

**Comment by ThomasPohl** [comment]
Hi Eddy, right now I am preparing a first release candidate. I still have a few errors in the ESQL parser. Probably I will publish the release candidate next week. It will require at least SonarQube Version 5.6.

**Comment by brunopenso** [comment]
Great!!! I tried but with no success.

Waiting for the release.

**Comment by EddyVos** [comment]
Great work ThomasPohl!

I also noticed that there where some issues with maven after compiling and loading the plugin into Sonar 5.6.6 (missing Guava library since SonarQube forgot to fix their plugin -- see https://github.com/SonarSource/sonar-packaging-maven-plugin/issues/9 ). I'm not looking to make a fix in the plugin and upload it in a branch on GitHub.

**Comment by ThomasPohl** [comment]
Thanks for testing the module, that helps a lot. 
Probably the guava library could be removed from the dependencies.  I will also do some testing with the 5.6.6 version.

**Comment by muthukumar-m** [comment]
Hi ThomasPohl,

Do you have any update for Sonar 5.6 compatibility issue?

**Comment by ThomasPohl** [comment]
Hi muthukumar-m,

I am not aware of any problems with SonarQube 5.6. Do you have a reproducible issue?
