### ISSUE TITLE
Fail to load plugin Esql Plugin

### ISSUE THREAD

**Issue by JohannBlais** [EXXETA/sonar-esql-plugin#92]
Hello,

I am using SonarQube 7.0 and I get this message when I try to use the plugin:

> java.lang.IllegalStateException: Fail to load plugin Esql Plugin [esql]
> 	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:88)
> 	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:585)
> 	at org.sonar.server.platform.Platform.start(Platform.java:211)
> 	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
> 	at org.sonar.server.platform.Platform.access$500(Platform.java:46)
> 	at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
> 	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
> 	at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
> 	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.NoClassDefFoundError: org/sonar/api/batch/AbstractSourceImporter
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
> 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
> 	at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
> 	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
> 	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
> 	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
> 	at com.exxeta.iss.sonar.esql.EsqlPlugin.getExtensions(EsqlPlugin.java:38)
> 	at org.sonar.api.SonarPlugin.define(SonarPlugin.java:51)
> 	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:78)
> 	... 9 common frames omitted
> Caused by: java.lang.ClassNotFoundException: org.sonar.api.batch.AbstractSourceImporter
> 	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
> 	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
> 	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
> 	... 25 common frames omitted
> 2018.03.23 08:07:21 INFO  web[][o.s.p.StopWatcher] Stopping process

Any idea ?

Thank you,
Johann

**Comment by ThomasPohl** [comment]
Sounds like the same as #91. I will check on that.

**Comment by ThomasPohl** [comment]
Which version of the ESQL plugin are you using? Looking at the stacktrace it seems like it's not the latest. Can you upgrade to 2.3.2 ?

**Comment by JohannBlais** [comment]
You were right, it was using an old version.
Seems to be working now.
Thanks
