### ISSUE TITLE
concatenating and logical operator

### ISSUE THREAD

**Issue by Ducatti** [EXXETA/sonar-esql-plugin#94]
Thomas,

When I try to concatenating UUIDASBLOB with UUIDASBLOB sonar think that pipes (||) is a logical operator and not a concatenating.
So im receving the issue "Correct one of the identical sub-expressions on both sides of operator "||""
But im not using as a logical operator but as a concatenating.

This is my code:
`SET uuid = SUBSTRING(CAST(UUIDASBLOB || UUIDASBLOB AS CHARACTER) FROM 3 FOR 48);`

**Comment by ThomasPohl** [comment]
Hi Ducatti,

you are right. That seems to be a bug. I will look into this and fix it.

Thanks for reporting.
