### ISSUE TITLE
Unable to parse ESQL with nested block comments

### ISSUE THREAD

**Issue by jfluitsma** [EXXETA/sonar-esql-plugin#96]
Hi Thomas,

I got an issue with nested comments in ESQL. It looks simitar to #83 but in our case the code is valid.
`/* -----------------------------
... lines ommitted
* Example CALL GFUNC_BrokerLog(
* /* ifName */ 'myTestFlow'
* /* msgCode */ 'KZ', /* msgType */ 'INF',
* /* srcSys */ 'srcFrom', /* srcMsg */ srcMsgBitStream,
* /* trgSys */ 'trgTo', /* trgMsg */ NULL,
* /* shrtDsc */ 'abc-def', /* longDsc */ NULL
* );
... lines ommitted
*/`

It is a long time ago I looked into the code so I hope you can find the solution quicker then I can.

Regards,
Jan Fluitsma

**Comment by ThomasPohl** [comment]
Hi Jan,
isn't there a comma missing? I would expect a comma after  'myTestFlow' and before 'INF'

Regards
Thomas

**Comment by ThomasPohl** [comment]
Hi Jan,

now understood the issue. That won't be easy. I am matching comments with regular expressions. Right now I have no idea how to specify a regex for these nested comments.
Nevertheless is it a bug in the plugin.

**Comment by jfluitsma** [comment]
Hi Thomas,

Thanks for the update. I also had looked into regexp with nested constructions, not easy.


Met vriendelijke groet,
With kind regards,

Jan Fluitsma
Integratie Specialist
+31 6 5375 7755

[cid:image001.jpg@01D40484.60E26170]
jan.fluitsma@virtualsciences.nl
www.virtualsciences.nl<http://www.virtualsciences.nl/>
Linkedin<https://www.linkedin.com/company-beta/27218/>
Twitter<https://twitter.com/virtualsciences>
Edisonbaan 15
3437 MN Nieuwegein

Bekijk hier de algemene voorwaarden van Conclusion<http://www.conclusion.nl/kleine-lettertjes/algemene-voorwaarden>

[cid:image002.jpg@01D40484.60E26170]
